### ISSUE TITLE
Cloudflare 503 when running in Github Actions

### ISSUE THREAD

**Issue by mattwynne** [nelson-social/bots#2]
I can run this locally and [it works](https://nelson.social/@WhitewaterBot/109601563054733106), but when I run it from GitHub Actions, we get [Cloudflare's bot detection page instead](https://github.com/nelson-social/whitewater-bot/actions/runs/3805712940/jobs/6473877466).

I'm not sure if we can do anything on our Cloudflare config to disable this, or whether we need to just bite the bullet and run it from somewhere else. Needs investigating.

**Comment by mattwynne** [comment]
@tillkruss do you know if it's possible (or desirable even?) to configure Cloudflare's Bot Manager to make an exception here and let these API calls through to the https://nelson.social server?

**Comment by tillkruss** [comment]
I can set up an exception. What’s the call exactly? User agent?

**Comment by keeth** [comment]
@mattwynne @tillkruss i think i am seeing this error too in the new TS version.  i am getting 503 on all API calls. 

The calls are things like:

`POST https://nelson.soclal/api/v2/media`
`GET https://nelson.soclal/api/v1/media/123`
`POST https://nelson.soclal/api/v1/statuses`


The user agent is `node-fetch` but I can customize it if we want to make a more specific exception rule.

**Comment by tillkruss** [comment]
Are you able to set a custom UA? Its a bit generic for an allowlist 🥲

**Comment by mattwynne** [comment]
I'm sure we can. We could use `whitewater-bot` for example?

**Comment by tillkruss** [comment]
So it looks like "Bot Fight Mode" can't be configured, I disabled it for now.

**Comment by mattwynne** [comment]
Sweet, that works for me! Thanks Till!
