### ISSUE TITLE
Configure secret tokens for two bots

### ISSUE THREAD

**Issue by keeth** [nelson-social/bots#4]
I refactored the code to support multiple bots:

```
MASTODON_TOKEN=${{ secrets.WHITEWATER_MASTODON_TOKEN }} npm run post-status whitewater
MASTODON_TOKEN=${{ secrets.AVALANCHE_MASTODON_TOKEN }} npm run post-status avalanche
```

I think we just need rename the existing secret and add a second one for the avalanche bot.

Hope this makes sense, open to feedback.

@mattwynne you OK creating a second bot account on nelson.social?

**Comment by mattwynne** [comment]
ON IT!

**Comment by mattwynne** [comment]
I am happy to share the credentials for logging in as the bots to nelson.socal with you @keeth but they still use my email address. We could consider getting Till to set up a bots@nelson.social group email or something, probably premature for that right now though?

**Comment by mattwynne** [comment]
Done! It works!

https://github.com/nelson-social/whitewater-bot/actions/runs/3825372295/jobs/6508465826
https://nelson.social/@AvalancheBot/109621959870049922
https://nelson.social/@WhitewaterBot/109621959472233030

I'm gonna make make some tweaks to the workflow and set up the scheduling.
